library(ape)
library(phangorn)
library(tidyverse)
setwd("/home/bella/Dropbox/Master-Thesis/MA_Thesis_Program/")
#table_dummy <- read.table("dummy_matrix.csv",header=TRUE,row.names = 1,sep = ",")
#table_nw <- read.csv("final_lev_mean_iranian.csv", header=TRUE,row.names = 1,sep=",")
#table_lv <- read.table("rom_matrix_lvst", header=TRUE,row.names = 1,sep=",")
table_nw <- read.table("rom_matrix_lvst",sep=",",header=TRUE,row.names = 1)
mx <- as.matrix(table_nw)
dm <- as.dist(mx)
t <- nj(dm)
plot(t)
na.omit(table_nw)
clus <- hclust(as.dist(table_nw),method ="average")
write.tree(phy=as.phylo(t),file="rom_nj2.newick")

clus1 <- njs(table_nw, fs = 15)
clus2 <- nj(as.matrix(table_nw))

trw <- nj(as.dist())
plot(t, main = "UPGMA Tree with Romance Data")
plot(clus2,main = "UPGMA Tree with Fictitious Data")
fastme.ols(clus)
